### ISSUE TITLE
Metadata and Collection Schema

### ISSUE THREAD

**Issue by Giorgionocera** [bitsongofficial/go-bitsong#182]
In the `nft` module, the `Collection` schema is the following
https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/proto/bitsong/nft/v1beta1/nft.proto#L42-L54
and includes `name` and `symbol` together with a `uri` field which can include data following a schema.

Similarly, the `Metadata` schema is the following 
https://github.com/bitsongofficial/go-bitsong/blob/84691c819214a1f9b9dd844ea2b49b7ccc8ece1b/proto/bitsong/nft/v1beta1/nft.proto#L14-L35
and includes `name` together with a `uri` field which can include data following a schema.

Since the schemas which are already available and much used as standards (like the one provided in https://nftschool.dev/reference/metadata-schemas/#intro-to-json-schemas which contains a reference to https://docs.opensea.io/docs/metadata-standards) uses to insert the `name` attribute inside the metadata, is it useful to also write it on the object stored on the chain?

**Comment by angelorc** [comment]
Agree with yout thoughts. I personally asked to add name, symbol and uri to keep some onchain specific data. Due to that we don't have any metadata standards I preferred to just keep name and symbol even in the collection.

For example if you list your collection on opensea, you will need to add uri name and some other field in an opensea db. Said that I prefer yo keep small data on chain

**Comment by go-btsg** [comment]
Which schema are you exactly looking for changes? can you point the fields to be removed or added per protobuf message?

**Comment by Giorgionocera** [comment]
I think Angelo said it is ok as it is right now.
